# Generated by Django 6.0 on 2025-12-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_apply_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='min_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
