# Generated by Django 6.0 on 2025-12-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='matching_mode',
            field=models.CharField(choices=[('skills', 'Skill Based'), ('resume', 'Resume (ATS) Based')], default='skills', max_length=10),
        ),
    ]
